### PR TITLE
More transcribing. Almost finished.

### PR DESCRIPTION
**Pull request by nlottig94**

### CODE REVIEW

**Comment by RJP43** [comment]
@nlottig94  thank you!

**Comment by nlottig94** [comment]
@rjp43 I do believe I'm going to run into a problem though. Look at the PDF.  I'm on the letters to the editor now, but there is no bottom half to the third page, so I don't know if it is going to work to transcribe these.

**Comment by RJP43** [comment]
Right I ran into the same problem when transcribing [Article 1888-08-19](https://github.com/RJP43/CitySlaveGirls/blob/master/Nelson_CSG/CSG_XML/1888-08-19-ChTimes.xml). So transcribe to a point that makes send then close out the div and the whole thing leaving a comment tag where you had to end saying where on the PDFs you transcribed to and the reason for not being able to transcribe further. You can reference my comment if you like.

**Comment by nlottig94** [comment]
Perfect!  Thank you!!

**Pull request merged**
